### ISSUE TITLE
launching gamesandstuff chrome app launches the website in chrome itself

### ISSUE THREAD

**Issue by Hoot679** [letsgoawaydev/gamesandstuff#9]

**Comment by letsgoawaydev** [comment]
yeah i just tried it and it does do that
ill try and fix it now

**Comment by letsgoawaydev** [comment]
ok so i went to uninstall programs in windows, uninstalled the games and stuff chrome app and the reinstalled it and it worked. i have no idea why

**Comment by Hoot679** [comment]
yeah that worked, chrome is broken.

**Comment by Hoot679** [comment]
yeah i think this is a chrome thing, because it keeps happening
